name: zesystem cdn

on:
  push:
    paths:
      - 'packages/main.js'
      - 'figma/token.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run node main.js
        run: node packages/main.js
        working-directory: .

