name: node app

on:
  push:
    paths:
      - 'figma/token.json'

jobs:
  actualizar-css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run main.js
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
        run: node packages/main.js

      - name: Add generated CSS files
        uses: actions/upload-artifact@v2
        with:
          name: generated-css
          path: |
            packages/*.css