
name: Node app

on:
  push:
    branches:
      - main
    paths:
      - 'packages/main.js'
      - 'figma/token.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: node packages/main.js
        working-directory: .
      - run: cp *.css packages/

