
name: Node app

on:
  push:
    paths:
      - 'packages/main.js'
      - 'figma/token.json'
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install dependencies
        run: npm install
      - name: run app 
        run: node packages/main.js
      - name: push css files
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add *.css
          git commit -m "Generated CSS files"
          git push
        
      