name: node app

on:
  push:
    paths:
      - 'figma/token.json'
    branches:
      - main

jobs:
  actualizar-css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Git
        run: |
          git config --global user.name 'CarvajalDev'
          git config --global user.email 'h_carvajal@outlook.es'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run main.js
        run: node packages/main.js

      - name: copy csss files to repository
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Add generated CSS files'
          add: 'packages/*.css'
          name: 'CarvajalDev'
          email: 'h_carvajal@outlook.es'
      
