
name: Node app

on:
  push:
    paths:
      - 'figma/token.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Check if token.json has changed
        id: check-changes
        run: |
          if [ -z "${{ github.event.before }}" ]; then
            before_commit="HEAD~1"
          else
            before_commit="${{ github.event.before }}"
          fi
          if [ -n "$(git diff --name-only $before_commit ${{ github.event.after }} figma/token.json)" ]; then
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "CHANGED=false" >> $GITHUB_ENV
          fi
      - name: Install dependencies
        if: steps.check-changes.outputs.CHANGED == 'true' # Solo si el archivo token.json ha cambiado
        run: npm install
      - name: Generate CSS files
        if: steps.check-changes.outputs.CHANGED == 'true' # Solo si el archivo token.json ha cambiado
        run: node packages/main.js
      - name: Copy CSS files to packages directory
        if: steps.check-changes.outputs.CHANGED == 'true' # Solo si el archivo token.json ha cambiado
        run: cp *.css packages/
