name: node app

on:
  push:
    paths:
      - 'figma/token.json'
    branches:
      - main

jobs:
  actualizar-css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'CarvajalDev'
          git config --global user.email 'h_carvajal@outlook.es'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run main.js
        run: node packages/main.js

      - name: Add CSS files to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USERNAME: 'CarvajalDev'
          GIT_EMAIL: 'h_carvajal@outlook.es'
        run: |
          git add packages/*.css
          git config --global user.name $GIT_USERNAME
          git config --global user.email $GIT_EMAIL
          git commit -m 'Add generated CSS files'
          git remote set-url origin https://github.com/CarvajalDev/zesystem-UI.git
          git push -u origin main

      
